### ISSUE TITLE
Missing file (Sirit.h)

### ISSUE THREAD

**Issue by alin742** [ReinUsesLisp/sirit#17]
The declaration file sirit.h is missing which makes a problem in building yuzu the switch emulator

**Comment by ReinUsesLisp** [comment]
yuzu builds fine for me and the declaration is present https://github.com/ReinUsesLisp/sirit/blob/f7c4b07a7e14edb1dcd93bc9879c823423705c2e/src/CMakeLists.txt#L2 .
Have you tried updating your submodules?

**Comment by ReinUsesLisp** [comment]
Closing. If this is still happens, please write here and I'll reopen it.
